#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

os="$(get_platform)"
arch="$(get_arch)"

if ! command -v go > /dev/null 2>&1; then
  zsh ~/.files/install/golang.sh
fi

if ! command -v caddy > /dev/null 2>&1; then
  xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/caddyserver/transform-encoder
fi

if [ -f /usr/local/bin/caddy ]; then
  echo 'setcap to /usr/local/bin/caddy'
  sudo setcap 'cap_net_bind_service=+ep' /usr/local/bin/caddy
fi

__echo__ 'installed: caddy with extra modules'
