#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

arch="$(get_arch)"

__echo__ 'installing required packages'

sudo apt install -y software-properties-common \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg

install_keyring

__echo__ 'installed: required packages'

__echo__ 'installing docker apt key & source'

pkgs=''

if (( $(check_ppa 'download.docker.com') < 1))
then
  if [ ! -f /etc/apt/keyrings/docker.asc ]; then
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
  fi

  if [ ! -f /etc/apt/sources.list.d/docker.list ]; then
    # shellcheck disable=SC1091
    echo \
      "deb [arch=${arch} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt update
  fi

  __echo__ 'installed: docker apt key & source'
fi

if ! command -v docker > /dev/null 2>&1 ; then
  pkgs="docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin"
fi

__echo__ "installing google gvisor apt source"

if [ ! -f /usr/share/keyrings/gvisor-archive-keyring.gpg ]; then
  curl -fsSL https://gvisor.dev/archive.key \
    | sudo gpg --dearmor -o /usr/share/keyrings/gvisor-archive-keyring.gpg
fi

if [ ! -f /etc/apt/sources.list.d/gvisor.list ]; then
  echo "deb [arch=${arch} signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main" \
    | sudo tee /etc/apt/sources.list.d/gvisor.list \
    > /dev/null

  sudo apt update
fi

__echo__ "installed: google gvisor apt source"

__echo__ 'installing docker-ce & co, and gvisor'

if ! command -v runsc > /dev/null 2>&1 ; then
  pkgs="${pkgs} runsc"
fi

if [ "" != "$pkgs" ]; then
  sudo apt install -y "$pkgs"
fi

__echo__ 'installed: docker-ce & co, and gvisor'
