#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

arch="$(get_arch)"

_run "sudo apt-get install -y software-properties-common apt-transport-https ca-certificates curl gnupg" 'Installing: required packages for docker'

install_keyring

_info 'installed: required packages'

_info 'installing: docker apt key & source'

pkgs=''

if (( $(check_ppa 'download.docker.com') < 1)); then
  if [ ! -f /etc/apt/keyrings/docker.asc ]; then
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
  fi

  if [ ! -f /etc/apt/sources.list.d/docker.list ]; then
    # shellcheck disable=SC1091
    echo \
      "deb [arch=${arch} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt-get update
  fi

  _info 'installed: docker apt key & source'
fi

if ! command -v docker > /dev/null 2>&1 ; then
  pkgs="docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin"
fi

_info 'installing: docker-ce & co'

if [ "" != "$pkgs" ]; then
  sudo apt-get update

  sudo apt-get install -y "$pkgs"
fi

_info 'installed: docker-ce & co'

if command -v docker > /dev/null 2>&1; then
  v=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" \
    | grep '"tag_name":' \
    | sed -E 's/.*"v([^"]+)".*/\1/')


  if ! command -v dive > /dev/null 2>&1 || \
    [[ "$v" != $(dive version | awk -F' ' '{print $2}') ]]
  then
    _run "eget wagoodman/dive --asset _linux_${arch}.deb" 'Downloading wagoodman/dive'
    _run "dpkg -i dive_${v}_linux_${arch}.deb" 'Installing: wagoodman/dive'

    sudo rm -f "./dive_${v}_linux_amd64.deb" &>/dev/null

    _info "dive is installed to: "$(command -v dive)""
  fi

  if ! command -v ctop > /dev/null 2>&1; then
    repo=https://github.com/bcicen/ctop
    v="$(gh_latest "$repo" | tr -d v)"

    _run  "eget bcicen/ctop --asset ctop-${v}-linux-${arch}.deb" "Installing: ctop"

    sudo wget \
      "$repo/releases/download/v${v}/ctop-${v}-linux-amd64" \
      -O /usr/local/bin/ctop
    sudo chmod +x /usr/local/bin/ctop > /dev/null 2>&1

  _info 'installed: ctop'
  fi
fi
