#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

os="$(get_platform)"
hw="$(get_hw)"

repo=https://github.com/dunglas/frankenphp
filename="frankenphp-${os}-${hw}"

_info 'downloading latest frankenphp release from github'

gh_dl "$repo" "$filename"
version="${version//v/}"

_info 'latest frankenphp release downloaded'

_info 'installing frankenphp'

if [ -f "$filename" ]; then
  sudo mv "$filename" /usr/local/bin/frankenphp
  sudo chmod a+x /usr/local/bin/frankenphp

  echo 'setcap to /usr/local/bin/frankenphp'
  sudo setcap 'cap_net_bind_service=+ep' /usr/local/bin/frankenphp
  sudo chown www-data: /usr/local/bin/frankenphp
fi

_info 'frankenphp installed'
