#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

if command -v gh ; then
  _error 'gh-cli has been installed, exiting'

  exit 1
fi

_info 'installing: gh-cli from github as root'

repo="https://github.com/cli/cli"

arc="$(get_arch)"
platform="$(get_platform)"
version="$(git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' https://github.com/cli/cli | tail --lines=1 | awk -F' ' '{print $2}' | awk -F'/' '{print $3}' | tr -d 'v')"

filename="gh_${version}_${platform}_${arc}.deb"

url="${repo}/releases/download/v${version}/$filename"

wget -qO $filename $url 2>&1

sudo dpkg -i "$filename"

_info 'installed: gh-cli from github as root'
