#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

__echo__ 'installing go packages as root'

names="duf fx xcaddy"

if ! command -v go > /dev/null 2>&1; then
  zsh ~/.files/install/golang.sh
fi

__echo__ "installing: $names"

sudo go install github.com/muesli/duf@latest
sudo go install github.com/antonmedv/fx@34.0.0
sudo go install github.com/caddyserver/xcaddy@latest

rootbin=/root/go/bin
bindir=/usr/local/bin

for name in duf fx xcaddy; do
  sudo chmod a+x "$rootbin/$name"

  sudo chown nobody:nogroup "$rootbin/$name"

  [ -f "$bindir/$name" ] && sudo rm -f "$bindir/$name"
  [ -L "$bindir/$name" ] && sudo rm -f "$bindir/$name"

  sudo mv "$rootbin/$name" "$bindir"

  sudo chown -h nobody:nogroup "$bindir/$name"
done

__echo__ "installed to /usr/local/bin/ => $names"
