#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

if (( $(check_ppa 'longsleep/golang-backports') < 1))
then
  _info "adding ppa:longsleep/golang-backports"

  sudo apt-get install -y curl ca-certificates

  sudo add-apt-repository -y ppa:longsleep/golang-backports

  _info "added: ppa:longsleep/golang-backports"
fi

if ! command -v go > /dev/null 2>&1; then
  sudo apt-get install -y golang-go
fi

_info 'golang installed, version info right below'

go version
