#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

version="$(gh_latest zyedidia/micro)"
normv="$(echo "$version" | sed 's.v..g')"
tar_file="micro-${normv}-linux64.tar.gz"

url=$(curl -s "https://api.github.com/repos/zyedidia/micro/releases/tags/${version}" \
  | jq '.assets.[].browser_download_url' \
  | grep '\-linux64.tar.gz' | grep -v .sha | sed 's."..g')

echo "Downloading micro from: ${url}"

cd /tmp/

if [ ! -f "/tmp/${tar_file}" ]; then
  wget -q --show-progress -O "/tmp/${tar_file}" $url
fi

if [ ! -f "/tmp/${tar_file}" ]; then
  echo "wget micro seems to fail, cannot find /tmp/${tar_file}"
  exit 1
fi

tar -xzf "${tar_file}"
rm -f "${tar_file}"

chmod a+x "micro-${normv}"
mv "micro-${normv}/micro" /usr/local/bin/micro
mv "micro-${normv}/micro.1" /usr/share/man/man1/

echo
echo
echo "micro installed to: /usr/local/bin/micro"
echo
echo

echo "Installing fzf & eza ..."

if [ ! -f /etc/apt/sources.list.d/gierens.list ]; then
  sudo mkdir -p /etc/apt/keyrings
  wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
  sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
fi

sudo apt update 1>/dev/null

sudo apt install -y fzf eza 1>/dev/null

echo
echo
echo "fzf installed to: $(which fzf)"
echo "eza installed to: $(which eza)"
echo
echo
