#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

if (( $(check_ppa 'ondrej/nginx-mainline') < 1))
then
  _info "adding ondrej's ppa"

  sudo add-apt-repository -y ppa:ondrej/nginx-mainline

  _info "ondrej's ppa added"
fi

_info 'installing nginx via apt'

sudo apt-get install -y nginx-full

_info 'nginx installed via apt'
