#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

if (( $(check_ppa 'ondrej/nginx-mainline') < 1))
then
  __echo__ "adding ondrej's ppa"

  sudo add-apt-repository -y ppa:ondrej/nginx-mainline

  __echo__ "ondrej's ppa added"
fi

__echo__ 'installing nginx via apt'

sudo apt install -y nginx-full

__echo__ 'nginx installed via apt'
