#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

_info "installing: percona's postgresql"

release_name="$(get_release_name)"

deb="percona-release_latest.${release_name}_all.deb"

wget -q "https://repo.percona.com/apt/$deb"

sudo dpkg -i $deb

sudo apt-get update
sudo percona-release setup ppg-16
sudo apt-get install -y percona-ppg-server-16
sudo systemctl status postgresql.service

_info "installed: percona's postgresql"
