#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

_info 'installing essential packages'

release_name="$(get_release_name)"

deb="percona-release_latest.${release_name}_all.deb"

wget -q "https://repo.percona.com/apt/$deb"

dpkg -i $deb

sudo apt update
sudo percona-release setup ppg-16
sudo apt install percona-ppg-server-16
sudo systemctl status postgresql.service 
