#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

if (( $(check_ppa 'ondrej/php') < 1))
then
  _info "adding ondrej's ppa"

  sudo add-apt-repository -y ppa:ondrej/php

  _info "ondrej's ppa added"
fi

_info 'installing php & redis via apt'

sudo apt-get install -y php7.4-fpm \
  php7.4-cli \
  php7.4-bcmath \
  php7.4-common \
  php7.4-curl \
  php7.4-gd \
  php7.4-igbinary \
  php7.4-imagick \
  php7.4-json \
  php7.4-mbstring \
  php7.4-opcache \
  php7.4-pgsql \
  php7.4-readline \
  php7.4-redis \
  php7.4-xml \
  php7.4-zip \
  redis-server

_info 'php & redis installed via apt'
