#!/usr/bin/env zsh

# shellcheck disable=SC1090
source ~/.files/functions.sh

# shellcheck disable=SC1090
source ~/.files/_install_funcs.sh

__echo__ 'installing essential packages'

release="$(get_release)"
release_name="$(get_release_name)"

arch="$(get_arch)"

pkgs="software-properties-common \
btop \
bzip2 \
curl \
dnsutils \
fail2ban \
git \
gzip \
jq \
htop \
nano \
redis-server \
traceroute \
tree \
unhide \
wget \
whois \
zip \
zstd"

cd /tmp || exit

if (( $(check_ppa 'git-core') < 1))
  sudo add-apt-repository -y ppa:git-core/ppa
fi

if [ "18.04" != "${release}" ] ; then
  pkgs="${pkgs} fzf micro"
fi

pkgs="$(echo "$pkgs" | tr -d '\n')"

_apt="sudo apt install -y ${pkgs}"

echo "$_apt"
eval "$_apt"


if ! command -v gh > /dev/null 2>&1 ; then
  install_keyring

  wget -qO- \
    https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    > /dev/null

  sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg

  echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    | sudo tee /etc/apt/sources.list.d/github-cli.list \
    > /dev/null 

  sudo apt update 

  sudo apt install -y gh
fi

if [ "18.04" == "${release}" ] ; then
  __echo__ 'installing micro & fzf'

  curl https://getmic.ro | bash

  sudo mv ./micro /usr/local/bin
  sudo chown root: /usr/local/bin/micro

  wget -q https://github.com/junegunn/fzf/releases/download/0.52.0/fzf-0.52.0-linux_"${arch}".tar.gz

  tar xzf fzf-0.52.0-linux_"${arch}".tar.gz

  sudo mv ./fzf /usr/local/bin
  sudo chown root: /usr/local/bin/fzf

  __echo__ 'installed: micro & fzf'
fi

if ! command -v bat > /dev/null 2>&1 ; then
  __echo__ 'installing bat'

  ver="0.24.0"
  repo=https://github.com/sharkdp/bat
  patt="bat_${ver}_${arch}.deb"

  if ! command -v gh > /dev/null 2>&1 ; then
    ver=$(gh_dl $repo "*_${arch}.deb")
  else
    wget -q "${repo}/releases/download/v${ver}/${patt}"
  fi

  patt="bat_${ver}_${arch}.deb"

  sudo dpkg -i "$patt"

  rm -f "$patt"

  __echo__ 'installed: bat'
fi

__echo__ 'essential packages installed'
